# Generated by Django 6.0 on 2025-12-18 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('mailing_messages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(help_text='С какого момента рассылка может быть запущена', verbose_name='Дата и время начала отправки')),
                ('end_time', models.DateTimeField(help_text='До какого момента разрешено выполнять отправку', verbose_name='Дата и время окончания отправки')),
                ('status', models.CharField(choices=[('Создана', 'Создана'), ('Запущена', 'Запущена'), ('Завершена', 'Завершена')], default='Создана', editable=False, max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_mailings', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailings', to='mailing_messages.message', verbose_name='Сообщение')),
                ('recipients', models.ManyToManyField(related_name='mailings', to='clients.client', verbose_name='Получатели')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='MailingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Успешно', 'Успешно'), ('Не успешно', 'Не успешно')], max_length=20, verbose_name='Статус')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Сообщение об ошибке')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время отправки')),
                ('server_response', models.TextField(blank=True, null=True, verbose_name='Ответ сервера')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailing_logs', to='clients.client', verbose_name='Клиент')),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='mailings.mailing', verbose_name='Рассылка')),
            ],
            options={
                'verbose_name': 'Лог отправки',
                'verbose_name_plural': 'Логи отправки',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.AddIndex(
            model_name='mailing',
            index=models.Index(fields=['start_time'], name='mailings_ma_start_t_4146e6_idx'),
        ),
        migrations.AddIndex(
            model_name='mailing',
            index=models.Index(fields=['end_time'], name='mailings_ma_end_tim_c26d25_idx'),
        ),
        migrations.AddIndex(
            model_name='mailing',
            index=models.Index(fields=['status'], name='mailings_ma_status_8e6188_idx'),
        ),
        migrations.AddIndex(
            model_name='mailing',
            index=models.Index(fields=['created_at'], name='mailings_ma_created_648b77_idx'),
        ),
        migrations.AddIndex(
            model_name='mailinglog',
            index=models.Index(fields=['sent_at'], name='mailings_ma_sent_at_d0f89e_idx'),
        ),
        migrations.AddIndex(
            model_name='mailinglog',
            index=models.Index(fields=['status'], name='mailings_ma_status_e16882_idx'),
        ),
        migrations.AddIndex(
            model_name='mailinglog',
            index=models.Index(fields=['mailing'], name='mailings_ma_mailing_8d78b8_idx'),
        ),
    ]
