# Generated by Django 6.0 on 2025-12-19 20:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailinglog',
            options={'ordering': ['-attempt_time'], 'verbose_name': 'Попытка рассылки', 'verbose_name_plural': 'Попытки рассылок'},
        ),
        migrations.RemoveIndex(
            model_name='mailinglog',
            name='mailings_ma_sent_at_d0f89e_idx',
        ),
        migrations.AddField(
            model_name='mailinglog',
            name='attempt_time',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Время создания записи о попытке отправки', verbose_name='Дата и время попытки'),
        ),
        migrations.AddField(
            model_name='mailinglog',
            name='client_email',
            field=models.EmailField(blank=True, help_text='Email адрес, на который отправлялось письмо', max_length=254, null=True, verbose_name='Email получателя'),
        ),
        migrations.AddField(
            model_name='mailinglog',
            name='message_subject',
            field=models.CharField(blank=True, help_text='Тема отправленного письма', max_length=255, null=True, verbose_name='Тема письма'),
        ),
        migrations.AlterField(
            model_name='mailinglog',
            name='server_response',
            field=models.TextField(blank=True, help_text='Ответ SMTP сервера при отправке письма', null=True, verbose_name='Ответ почтового сервера'),
        ),
        migrations.AddIndex(
            model_name='mailinglog',
            index=models.Index(fields=['attempt_time'], name='mailings_ma_attempt_4dee1e_idx'),
        ),
        migrations.AddIndex(
            model_name='mailinglog',
            index=models.Index(fields=['client_email'], name='mailings_ma_client__1d9955_idx'),
        ),
        migrations.RemoveField(
            model_name='mailinglog',
            name='client',
        ),
        migrations.RemoveField(
            model_name='mailinglog',
            name='error_message',
        ),
    ]
