# Generated by Django 6.0 on 2025-12-20 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('mailings', '0002_alter_mailinglog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailinglog',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mailing_logs', to='clients.client', verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='mailinglog',
            name='error_message',
            field=models.TextField(blank=True, help_text='Подробное сообщение об ошибке', null=True, verbose_name='Сообщение об ошибке'),
        ),
        migrations.AddIndex(
            model_name='mailinglog',
            index=models.Index(fields=['client'], name='mailings_ma_client__fb01b1_idx'),
        ),
    ]
