# Generated by Django 6.0 on 2025-12-11 21:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Введите действительный email адрес', max_length=255, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Email')),
                ('full_name', models.CharField(help_text='Введите полное имя клиента', max_length=200, verbose_name='Ф. И. О.')),
                ('comment', models.TextField(blank=True, help_text='Дополнительная информация о клиенте', null=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='clients_cli_email_56b9fc_idx'), models.Index(fields=['created_at'], name='clients_cli_created_4ff9ec_idx')],
            },
        ),
    ]
